/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List upcoming bookings across all event types in a single list,
         *     ordered by start time.
         */
        get: operations["AdminBookings_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all event types, including inactive ones. */
        get: operations["AdminEventTypes_list"];
        put?: never;
        /** @description Create a new event type. */
        post: operations["AdminEventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Create a booking on a chosen slot.
         *     Fails with 409 if the time range overlaps any existing booking
         *     (busy rule is global across all event types for the owner).
         */
        post: operations["Bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a booking by id. */
        get: operations["Bookings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all active event types available to guests. */
        get: operations["EventTypes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single event type by id. */
        get: operations["EventTypes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List free, bookable slots for an event type over the next 14 days.
         *     Slots are generated from the owner's weekly availability, stepped by the
         *     event type duration, excluding any time that overlaps an existing booking.
         */
        get: operations["EventTypes_slots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A confirmed reservation made by a guest. */
        Booking: {
            /** Format: int64 */
            readonly id: number;
            /**
             * Format: int64
             * @description The event type this booking belongs to.
             */
            eventTypeId: number;
            /** @description Guest display name. */
            guestName: string;
            /**
             * Format: email
             * @description Guest email address.
             */
            guestEmail: string;
            /**
             * Format: date-time
             * @description Inclusive start of the booking (ISO-8601, UTC).
             */
            start: string;
            /**
             * Format: date-time
             * @description Exclusive end of the booking (ISO-8601, UTC).
             */
            readonly end: string;
            readonly status: components["schemas"]["BookingStatus"];
            /** Format: date-time */
            readonly createdAt: string;
        };
        /** @description Payload to create a booking on a chosen slot (guest). */
        BookingCreate: {
            /**
             * Format: int64
             * @description The event type to book.
             */
            eventTypeId: number;
            guestName: string;
            /** Format: email */
            guestEmail: string;
            /**
             * Format: date-time
             * @description Start of the chosen slot (must match a free slot in the 14-day window).
             */
            start: string;
        };
        /**
         * @description Booking lifecycle status.
         * @enum {string}
         */
        BookingStatus: "CONFIRMED" | "CANCELLED";
        /** @description Standard error payload returned for non-2xx responses. */
        Error: {
            /** @description Machine-readable error code, e.g. "SLOT_TAKEN", "NOT_FOUND", "VALIDATION_ERROR". */
            code: string;
            /** @description Human-readable description of the error. */
            message: string;
        };
        /** @description A type of meeting the owner offers (e.g. "30 min intro call"). */
        EventType: {
            /**
             * Format: int64
             * @description Unique identifier of the event type.
             */
            readonly id: number;
            /** @description Display name shown to guests. */
            title: string;
            /** @description Description shown to guests. */
            description: string;
            /**
             * Format: int32
             * @description Meeting length in minutes. Also used as the slot step.
             */
            durationMinutes: number;
            /** @description Whether the event type is visible/bookable by guests. */
            active: boolean;
        };
        /** @description Payload to create a new event type (owner/admin). */
        EventTypeCreate: {
            title: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
            /**
             * @description Defaults to true when omitted.
             * @default true
             */
            active: boolean;
        };
        /** @description A free, bookable time range for a given event type. */
        Slot: {
            /**
             * Format: date-time
             * @description Inclusive start of the slot (ISO-8601, UTC).
             */
            start: string;
            /**
             * Format: date-time
             * @description Exclusive end of the slot (ISO-8601, UTC).
             */
            end: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminBookings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    AdminEventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    AdminEventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Bookings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    EventTypes_slots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
