name: Scheduled OpenCode Task

on:
  schedule:
    - cron: "* * * * *" # каждую минуту
  workflow_dispatch: # ручной запуск

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 24.x
        uses: actions/setup-node@v3
        with:
          node-version: 24.x
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.15.x
          cd .\frontend\
          lhci autorun